export const REQUEST_TYPE = "_REQUEST";
export const SUCCESS_TYPE = "_SUCCESS";
export const FAILURE_TYPE = "_FAILURE";
export const SET_LEADER_TYPE = "SET_LEADER_TYPE";
export const LOGIN_TYPE = "LOGIN";
export const LOGOUT_TYPE = "LOGOUT_TYPE";
export const GET_USER_TYPE = "GET_USER_TYPE";
export const CLEAR_ERROR = "CLEAR_ERROR";

// Display for responsive
export const SET_PAGE_DISPLAY_MODE = "SET_PAGE_DISPLAY_MODE";
export const SET_CLICK_CHAT = "SET_CLICK_CHAT";

// Detail News
export const DETAIL_NEWS_REQ = "DETAIL_NEWS_REQ";
export const DETAIL_NEWS_SUCCESS = "DETAIL_NEWS_SUCCESS";
export const DETAIL_NEWS_FAILED = "DETAIL_NEWS_FAILED";
export const DETAIL_NEWS_LIST_REQ = "DETAIL_NEWS_LIST_REQ";
export const DETAIL_NEWS_LIST_SUCCESS = "DETAIL_NEWS_LIST_SUCCESS";
export const DETAIL_NEWS_LIST_FAILED = "DETAIL_NEWS_LIST_FAILED";

// List News
export const LIST_NEWS_REQ = "LIST_NEWS_REQ";
export const LIST_NEWS_SUCCESS = "LIST_NEWS_SUCCESS";
export const LIST_NEWS_FAILED = "LIST_NEWS_FAILED";

// News Attribute
export const PROFILE_NEWS_REQ = "PROFILE_NEWS_REQ";
export const PROFILE_NEWS_SUCCESS = "PROFILE_NEWS_SUCCESS";
export const PROFILE_NEWS_FAILED = "PROFILE_NEWS_FAILED";
export const MAIN_NEWS_REQ = "MAIN_NEWS_REQ";
export const MAIN_NEWS_SUCCESS = "MAIN_NEWS_SUCCESS";
export const MAIN_NEWS_FAILED = "MAIN_NEWS_FAILED";
// List News Home
export const LIST_NEWS_HOME_REQ = "LIST_NEWS_HOME_REQ";
export const LIST_NEWS_HOME_SUCCESS = "LIST_NEWS_HOME_SUCCESS";
export const LIST_NEWS_HOME_FAILED = "LIST_NEWS_HOME_FAILED";

// List News Additional
export const LIST_NEWS_ADDITIONAL_REQ = "LIST_NEWS_ADDITIONAL_REQ";
export const LIST_NEWS_ADDITIONAL_SUCCESS = "LIST_NEWS_ADDITIONAL_SUCCESS";
export const LIST_NEWS_ADDITIONAL_FAILED = "LIST_NEWS_ADDITIONAL_FAILED";

// Billing Address
export const BILLING_ADDRESS_REQ = "BILLING_ADDRESS_REQ";
export const BILLING_ADDRESS_SUCCESS = "BILLING_ADDRESS_SUCCESS";
export const BILLING_ADDRESS_FAILED = "BILLING_ADDRESS_FAILED";
export const BILLING_ADDRESS_PUT_REQ = "BILLING_ADDRESS_PUT_REQ";
export const BILLING_ADDRESS_PUT_SUCCESS = "BILLING_ADDRESS_PUT_SUCCESS";
export const BILLING_ADDRESS_PUT_FAILED = "BILLING_ADDRESS_PUT_FAILED";
export const BILLING_ADDRESS_POST_REQ = "BILLING_ADDRESS_POST_REQ";
export const BILLING_ADDRESS_POST_SUCCESS = "BILLING_ADDRESS_POST_SUCCESS";
export const BILLING_ADDRESS_POST_FAILED = "BILLING_ADDRESS_POST_FAILED";
export const INFO_BILLING_ADDRESS = "INFO_BILLING_ADDRESS";
export const PURCHASE_SUMMARY_REQ = "PURCHASE_SUMMARY_REQ";
export const PURCHASE_SUMMARY_SUCCESS = "PURCHASE_SUMMARY_SUCCESS";
export const PURCHASE_SUMMARY_FAILED = "PURCHASE_SUMMARY_FAILED";
export const ATTRIBUTE_NAME_REQ = "ATTRIBUTE_NAME_REQ";
export const ATTRIBUTE_NAME_SUCCESS = "ATTRIBUTE_NAME_SUCCESS";
export const ATTRIBUTE_NAME_FAILED = "ATTRIBUTE_NAME_FAILED";
export const CONTACT_INFORMATION_PUT_REQ = "CONTACT_INFORMATION_PUT_REQ";
export const CONTACT_INFORMATION_PUT_SUCCESS = "CONTACT_INFORMATION_PUT_SUCCESS";
export const CONTACT_INFORMATION_PUT_FAILED = "CONTACT_INFORMATION_PUT_FAILED";
export const CONTACT_INFORMATION_POST_REQ = "CONTACT_INFORMATION_POST_REQ";
export const CONTACT_INFORMATION_POST_SUCCESS = "CONTACT_INFORMATION_POST_SUCCESS";
export const CONTACT_INFORMATION_POST_FAILED = "CONTACT_INFORMATION_POST_FAILED";

// Brand
export const BRAND_REQ = "BRAND_REQ";
export const BRAND_SUCCESS = "BRAND_SUCCESS";
export const BRAND_FAILED = "BRAND_FAILED";

// Detail Product
export const DETAIL_PRODUCT_REQ = "DETAIL_PRODUCT_REQ";
export const DETAIL_PRODUCT_SUCCESS = "DETAIL_PRODUCT_SUCCESS";
export const DETAIL_PRODUCT_FAILED = "DETAIL_PRODUCT_FAILED";
export const DETAIL_PRODUCT_RELATED_REQ = "DETAIL_PRODUCT_RELATED_REQ";
export const DETAIL_PRODUCT_RELATED_SUCCESS = "DETAIL_PRODUCT_RELATED_SUCCESS";
export const DETAIL_PRODUCT_RELATED_FAILED = "DETAIL_PRODUCT_RELATED_FAILED";
export const DETAIL_PRODUCT_REVIEW_REQ = "DETAIL_PRODUCT_REVIEW_REQ";
export const DETAIL_PRODUCT_REVIEW_SUCCESS = "DETAIL_PRODUCT_REVIEW_SUCCESS";
export const DETAIL_PRODUCT_REVIEW_FAILED = "DETAIL_PRODUCT_REVIEW_FAILED";

//List Product
export const LIST_PRODUCT_REQ = "LIST_PRODUCT_REQ";
export const LIST_PRODUCT_SUCCESS = "LIST_PRODUCT_SUCCESS";
export const LIST_PRODUCT_FAILED = "LIST_PRODUCT_FAILED";

// Reset Initial State
export const RESET_INITIAL_STATE = "RESET_INITIAL_STATE";

//CART
export const CART_LIST_REQ = "CART_LIST_REQ";
export const CART_LIST_SUCCESS = "CART_LIST_SUCCESS";
export const CART_LIST_FAILED = "CART_LIST_FAILED";
export const POST_CART_REQ = "POST_CART_REQ";
export const POST_CART_SUCCESS = "POST_CART_SUCCESS";
export const POST_CART_FAILED = "POST_CART_FAILED";
export const CART_DETAIL_FAILED = "CART_DETAIL_FAILED";
export const CART_DETAIL_SUCCESS = "CART_DETAIL_SUCCESS";
export const CART_DETAIL_REQ = "CART_DETAIL_REQ";
export const CREATE_SO_REQ = "CREATE_SO_REQ";
export const CREATE_SO_SUCCESS = "CREATE_SO_SUCCESS";
export const CREATE_SO_FAILED = "CREATE_SO_FAILED";
export const CHANGE_STATUS_REQ = "CHANGE_STATUS_REQ";
export const CHANGE_STATUS_SUCCESS = "CHANGE_STATUS_SUCCESS";
export const CHANGE_STATUS_FAILED = "CHANGE_STATUS_FAILED";
export const UPLOADATTACH_SO_FAILED = "UPLOADATTACH_SO_FAILED";
export const UPLOADATTACH_SO_REQ = "UPLOADATTACH_SO_REQ";
export const UPLOADATTACH_SO_SUCCESS = "UPLOADATTACH_SO_SUCCESS";


//Category
export const CATEGORY_REQ = "CATEGORY_REQ";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAILED = "CATEGORY_FAILED";

//USER PROFILE
export const USER_PROFILE_REQ = "USER_PROFILE_REQ";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILED = "USER_PROFILE_FAILED";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const VERIFY_CODE = "VERIFY_CODE";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

//PROMOTION
export const IMAGE_SLIDER_REQ = "IMAGE_SLIDER_REQ";
export const IMAGE_SLIDER_SUCCESS = "IMAGE_SLIDER_SUCCESS";
export const IMAGE_SLIDER_FAILED = "IMAGE_SLIDER_FAILED";
export const PROMOTION_LIST_REQ = "PROMOTION_LIST_REQ";
export const PROMOTION_LIST_SUCCESS = "PROMOTION_LIST_SUCCESS";
export const PROMOTION_LIST_FAILED = "PROMOTION_LIST_FAILED";
export const PROMOTION_DETAIL_REQ = "PROMOTION_DETAIL_REQ";
export const PROMOTION_DETAIL_SUCCESS = "PROMOTION_DETAIL_SUCCESS";
export const PROMOTION_DETAIL_FAILED = "PROMOTION_DETAIL_FAILED";
export const PROMOTION_HEADER_LIST_REQ = "PROMOTION_HEADER_LIST_REQ";
export const PROMOTION_HEADER_LIST_SUCCESS = "PROMOTION_HEADER_LIST_SUCCESS";
export const PROMOTION_HEADER_LIST_FAILED = "PROMOTION_HEADER_LIST_FAILED";

// VOUCHER
export const VOUCHER_ALL_REQ = "VOUCHER_ALL_REQ";
export const VOUCHER_ALL_SUCCESS = "VOUCHER_ALL_SUCCESS";
export const VOUCHER_ALL_FAILED = "VOUCHER_ALL_FAILED";
export const VOUCHER_DETAIL_REQ = "VOUCHER_DETAIL_REQ";
export const VOUCHER_DETAIL_SUCCESS = "VOUCHER_DETAIL_SUCCESS";
export const VOUCHER_DETAIL_FAILED = "VOUCHER_DETAIL_FAILED";
export const VOUCHER_CLAIMED_REQ = "VOUCHER_CLAIMED_REQ";
export const VOUCHER_CLAIMED_SUCCESS = "VOUCHER_CLAIMED_SUCCESS";
export const VOUCHER_CLAIMED_FAILED = "VOUCHER_CLAIMED_FAILED";
export const CLAIM_VOUCHER_REQ = "CLAIM_VOUCHER_REQ";
export const CLAIM_VOUCHER_SUCCESS = "CLAIM_VOUCHER_SUCCESS";
export const CLAIM_VOUCHER_FAILED = "CLAIM_VOUCHER_FAILED";

//TERM CONDITION
export const TERM_CONDITION_REQ = "TERM_CONDITION_REQ";
export const TERM_CONDITION_SUCCESS = "TERM_CONDITION_SUCCESS";
export const TERM_CONDITION_FAILED = "TERM_CONDITION_FAILED";
export const PUT_TERM_CONDITION_REQ = "PUT_TERM_CONDITION_REQ";
export const PUT_TERM_CONDITION_SUCCESS = "PUT_TERM_CONDITION_SUCCESS";
export const PUT_TERM_CONDITION_FAILED = "PUT_TERM_CONDITION_FAILED";

export const CHECK_CUSTOMER = "CHECK_CUSTOMER"
export const CHECK_STATUS = "CHECK_STATUS"

// DOWNLOAD AND UPLOAD
export const DOWNLOAD_CSV_FAILED = "DOWNLOAD_CSV_FAILED";
export const DOWNLOAD_CSV_REQ = "DOWNLOAD_CSV_REQ";
export const DOWNLOAD_CSV_SUCCESS = "DOWNLOAD_CSV_SUCCESS";
export const UPLOAD_CSV_REQ = "UPLOAD_CSV_REQ";
export const UPLOAD_CSV_SUCCESS = "UPLOAD_CSV_SUCCESS";
export const UPLOAD_CSV_FAILED = "UPLOAD_CSV_FAILED";
export const UPLOAD_FILE_REQ = "UPLOAD_FILE_REQ";
export const UPLOAD_FILE_FAILED = "UPLOAD_FILE_FAILED";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";

// BRANCH
export const BRANCH_LIST_REQ = "BRANCH_LIST_REQ";
export const BRANCH_LIST_FAILED = "BRANCH_LIST_FAILED";
export const BRANCH_LIST_SUCCESS = "BRANCH_LIST_SUCCESS";

export const SIGNUP = 'SIGNUP';

// SEARCH
export const SEARCH_SUGGESTION_LIST_REQ = "SEARCH_SUGGESTION_LIST_REQ";
export const SEARCH_SUGGESTION_LIST_SUCCESS = "SEARCH_SUGGESTION_LIST_SUCCESS";
export const SEARCH_SUGGESTION_LIST_FAILED = "SEARCH_SUGGESTION_LIST_FAILED";

// CHECKSTOCK
export const CHECKSTOCK_FAILED = "CHECKSTOCK_FAILED";
export const CHECKSTOCK_REQ = "CHECKSTOCK_REQ";
export const CHECKSTOCK_SUCCESS = "CHECKSTOCK_SUCCESS";

// SEARCH BY USERID
export const SEARCH_BY_USERID_REQ = "SEARCH_BY_USERID_REQ";
export const SEARCH_BY_USERID_SUCCESS = "SEARCH_BY_USERID_SUCCESS";
export const SEARCH_BY_USERID_FAILED = "SEARCH_BY_USERID_FAILED";

// CART BY CARTID
export const CART_LIST_BY_CARTID_REQ = "CART_LIST_BY_CARTID_REQ";
export const CART_LIST_BY_CARTID_SUCCESS = "CART_LIST_BY_CARTID_SUCCESS";
export const CART_LIST_BY_CARTID_FAILED = "CART_LIST_BY_CARTID_FAILED";
export const CART_LIST_BY_CARTID_PUT_REQ = "CART_LIST_BY_CARTID_PUT_REQ";
export const CART_LIST_BY_CARTID_PUT_SUCCESS = "CART_LIST_BY_CARTID_PUT_SUCCESS";
export const CART_LIST_BY_CARTID_PUT_FAILED = "CART_LIST_BY_CARTID_PUT_FAILED";
export const CART_LIST_BY_CARTID_DELETE_REQ = "CART_LIST_BY_CARTID_DELETE_REQ";
export const CART_LIST_BY_CARTID_DELETE_SUCCESS = "CART_LIST_BY_CARTID_DELETE_SUCCESS";
export const CART_LIST_BY_CARTID_DELETE_FAILED = "CART_LIST_BY_CARTID_DELETE_FAILED";
export const CART_BY_DETAILID_DELETE_REQ = "CART_BY_DETAILID_DELETE_REQ";
export const CART_BY_DETAILID_DELETE_SUCCESS = "CART_BY_DETAILID_DELETE_SUCCESS";
export const CART_BY_DETAILID_DELETE_FAILED = "CART_BY_DETAILID_DELETE_FAILED";
export const CART_PURCHASE_CHECKOUT_REQ = "CART_PURCHASE_CHECKOUT_REQ";
export const CART_PURCHASE_CHECKOUT_SUCCESS = "CART_PURCHASE_CHECKOUT_SUCCESS";
export const CART_PURCHASE_CHECKOUT_FAILED = "CART_PURCHASE_CHECKOUT_FAILED";
export const CART_CHECKOUT_PRODUCT_REQ = "CART_CHECKOUT_PRODUCT_REQ";
export const CART_CHECKOUT_PRODUCT_SUCCESS = "CART_CHECKOUT_PRODUCT_SUCCESS";
export const CART_CHECKOUT_PRODUCT_FAILED = "CART_CHECKOUT_PRODUCT_FAILED"

// CHECKPRICE
export const CHECKPRICE_REQ = "CHECKPRICE_REQ";
export const CHECKPRICE_SUCCESS = "CHECKPRICE_SUCCESS";
export const CHECKPRICE_FAILED = "CHECKPRICE_FAILED";

// TRANSACTION
export const TRANSACTION_POST_REQ = "TRANSACTION_POST_REQ";
export const TRANSACTION_POST_SUCCESS = "TRANSACTION_POST_SUCCESS";
export const TRANSACTION_POST_FAILED = "TRANSACTION_POST_FAILED";
export const TRANSACTION_ORDER = "TRANSACTION_ORDER";
export const TRANSACTION_DETAIL = "TRANSACTION_DETAIL";

// ORDER TIMELINE
export const TIMELINE_GET_REQ = 'TIMELINE_GET_REQ';
export const TIMELINE_GET_SUCCESS = 'TIMELINE_GET_SUCCESS';
export const TIMELINE_GET_FAILED = 'TIMELINE_GET_FAILED';

// Block Login
export const RELEASE_BLOCKED_LOGIN = "RELEASE_BLOCKED_LOGIN";
export const SET_BLOCK_LOGIN = "SET_BLOCK_LOGIN";
export const COUNT_FAILED_LOGIN = "COUNT_FAILED_LOGIN";
export const COUNT_DOWN_TIMER_LOCK = "COUNT_DOWN_TIMER_LOCK";
export const INITIAL_FAILED_LOGIN_STATUS = "INITIAL_FAILED_LOGIN_STATUS";

// SEARCH DISTRICT
export const SEARCH_DISTRICT_FAILED = "SEARCH_DISTRICT_FAILED";
export const SEARCH_DISTRICT_REQ = "SEARCH_DISTRICT_REQ";
export const SEARCH_DISTRICT_SUCCESS = "SEARCH_DISTRICT_SUCCESS";

// POSTAL CODE
export const POSTAL_CODE_FAILED = "POSTAL_CODE_FAILED";
export const POSTAL_CODE_REQ = "POSTAL_CODE_REQ";
export const POSTAL_CODE_SUCCESS = "POSTAL_CODE_SUCCESS";

// PAYMENT
export const PAYMENT_FAILED = "PAYMENT_FAILED";
export const PAYMENT_REQ = "PAYMENT_REQ";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_METHOD_REQ = "PAYMENT_METHOD_REQ";
export const PAYMENT_METHOD_SUCCESS = "PAYMENT_METHOD_SUCCESS";
export const PAYMENT_METHOD_FAILED = "PAYMENT_METHOD_FAILED";

// IMAGE PROFILE
export const IMAGE_PROFILE_GLOBAL = 'IMAGE_PROFILE_GLOBAL';
export const CHANGE_PROFILE_FAILED = "CHANGE_PROFILE_FAILED";
export const CHANGE_PROFILE_REQ = "CHANGE_PROFILE_REQ";
export const CHANGE_PROFILE_SUCCESS = "CHANGE_PROFILE_SUCCESS";

// WISHLIST
export const WISHLIST_GET_REQ = 'WISHLIST_GET_REQ';
export const WISHLIST_GET_SUCCESS = 'WISHLIST_GET_SUCCESS';
export const WISHLIST_GET_FAILED = 'WISHLIST_GET_FAILED';
export const WISHLIST_POST_REQ = 'WISHLIST_POST_REQ';
export const WISHLIST_POST_SUCCESS = 'WISHLIST_POST_SUCCESS';
export const WISHLIST_POST_FAILED = 'WISHLIST_POST_FAILED';
export const WISHLIST_DEL_REQ = 'WISHLIST_DEL_REQ';
export const WISHLIST_DEL_SUCCESS = 'WISHLIST_DEL_SUCCESS';
export const WISHLIST_DEL_FAILED = 'WISHLIST_DEL_FAILED';
export const WISHLIST_DEL_BULK_REQ = 'WISHLIST_DEL_BULK_REQ';
export const WISHLIST_DEL_BULK_SUCCESS = 'WISHLIST_DEL_BULK_SUCCESS';
export const WISHLIST_DEL_BULK_FAILED = 'WISHLIST_DEL_BULK_FAILED';

// REVIEW PRODUCT
export const POST_REVIEW_PRODUCT_REQ = "POST_REVIEW_PRODUCT_REQ";
export const POST_REVIEW_PRODUCT_SUCCESS = "POST_REVIEW_PRODUCT_SUCCESS";
export const POST_REVIEW_PRODUCT_FAILED = "POST_REVIEW_PRODUCT_FAILED";

// FORWARDER
export const GET_TIMELINE_FORWARDER_REQ = "GET_TIMELINE_FORWARDER_REQ";
export const GET_TIMELINE_FORWARDER_SUCCESS = "GET_TIMELINE_FORWARDER_SUCCESS";
export const GET_TIMELINE_FORWARDER_FAILED = "GET_TIMELINE_FORWARDER_FAILED";

// VIDEO
export const GET_VIDEO_ALL_REQ = "GET_VIDEO_ALL_REQ";
export const GET_VIDEO_ALL_SUCCESS = "GET_VIDEO_ALL_SUCCESS";
export const GET_VIDEO_ALL_FAILED = "GET_VIDEO_ALL_FAILED";
export const GET_VIDEO_DETAIL_REQ = "GET_VIDEO_DETAIL_REQ";
export const GET_VIDEO_DETAIL_SUCCESS = "GET_VIDEO_DETAIL_SUCCESS";
export const GET_VIDEO_DETAIL_FAILED = "GET_VIDEO_DETAIL_FAILED";

// SHIPMENT
export const SHIPMENT_METHOD_REQ = "SHIPMENT_METHOD_REQ";
export const SHIPMENT_METHOD_SUCCESS = "SHIPMENT_METHOD_SUCCESS";
export const SHIPMENT_METHOD_FAILED = "SHIPMENT_METHOD_FAILED";

// CANCEL ORDER
export const LIST_CANCEL_REQ = "LIST_CANCEL_REQ";
export const LIST_CANCEL_SUCCESS = "LIST_CANCEL_SUCCESS";
export const LIST_CANCEL_FAILED = "LIST_CANCEL_FAILED";
export const CANCEL_REASON_PATCH_REQ = "CANCEL_REASON_PATCH_REQ";
export const CANCEL_REASON_PATCH_SUCCESS = "CANCEL_REASON_PATCH_SUCCESS";
export const CANCEL_REASON_PATCH_FAILED = "CANCEL_REASON_PATCH_FAILED";

// FAKTUR PAJAK & INVOICE
export const DOWNLOAD_FAKTUR_PAJAK_REQ = "DOWNLOAD_FAKTUR_PAJAK_REQ";
export const DOWNLOAD_FAKTUR_PAJAK_SUCCESS = "DOWNLOAD_FAKTUR_PAJAK_SUCCESS";
export const DOWNLOAD_FAKTUR_PAJAK_FAILED = "DOWNLOAD_FAKTUR_PAJAK_FAILED";
export const DOWNLOAD_INVOICE_REQ = "DOWNLOAD_INVOICE_REQ";
export const DOWNLOAD_INVOICE_SUCCESS = "DOWNLOAD_INVOICE_SUCCESS";
export const DOWNLOAD_INVOICE_FAILED = "DOWNLOAD_INVOICE_FAILED";

// ORDER_RECEIVED
export const ORDER_RECEIVED_PATCH_REQ = "ORDER_RECEIVED_PATCH_REQ";
export const ORDER_RECEIVED_PATCH_SUCCESS = "ORDER_RECEIVED_PATCH_SUCCESS";
export const ORDER_RECEIVED_PATCH_FAILED = "ORDER_RECEIVED_PATCH_FAILED";

// FITUR UT CONNECT
export const GET_FITUR_UTCONNECT_REQ = "GET_FITUR_UTCONNECT_REQ";
export const GET_FITUR_UTCONNECT_FAILED = "GET_FITUR_UTCONNECT_FAILED";
export const GET_FITUR_UTCONNECT_SUCCESS = "GET_FITUR_UTCONNECT_SUCCESS";