 const CONDITIONCODE = {
    GOOD: 'NMG',
    BAD: 'NMB',
    UNCHECK: 'NMU',
    FLUID_LOW: 'FLL',
    FLUID_MEDIUM: 'FLM',
    FLUID_HIGH: 'FLH',
    VIOLANCE_SOFT: 'SVS',
    VIOLANCE_HARD: 'SVH',
    SOIL_THICK_CLEAN: 'TSC',
    SOIL_THICK_MEDIUM: 'TSM',
    SOIL_THICK_HIGH: 'TSH',
    REFRIGRERANT_EMPTY: 'TSE',
    REFRIGRERANT_LOW: 'RFL',
    REFRIGRERANT_HIGH: 'RFH',
    GRACE25: 'GRD',
    GRADE50: 'GRL',
    GRACE75: 'GRT',
    GRACE100: 'GRS',
    PAGE_PRODUCT_LIST: 16,
    PAGE_SEARCH: 5,
  };
export default CONDITIONCODE;
  