export const AreaChecksheets = [
    {
        "ZoneDesc": "ZONE 1 FRONT & UPPER AREA",
        "Area": "A. FRONT SIDE OF MACHINE CHECK",
        "GoodCondition": 9,
        "BadCondition": 0,
        "UncheckCondition": 0,
        "CheckSheetValues": [
            {
                "WoId": "47284214-faf8-464f-a967-d26a8cf0675e",
                "BacklogId": null,
                "WoNumber": "70156080",
                "UnitModel": "HD785-7",
                "SerialNumber": "9402",
                "UnitCode": "DT4112",
                "EquipmentNumber": "106921",
                "FormNumber": "HD785-7/3402/00/QA10/13(5)",
                "ZoneDesc": "ZONE 1 FRONT & UPPER AREA",
                "AreaDesc": "A. FRONT SIDE OF MACHINE CHECK",
                "ItemDesc": "Abnormal noise and discuss with operator (get opinion)",
                "Version": "1.00",
                "Measurement": "0",
                "Sequence": 1,
                "MPriority": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MNote": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MCondition": {
                    "Measurement": null,
                    "TypeDesc": "0",
                    "Code": "NMG",
                    "Desc": "Good",
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "Comment": null,
                "LeaderApprovedBy": "80101070@unitedtractors.com",
                "LeaderApprovedDate": "2020-04-21T10:02:03.291",
                "SupervisorApprovedDate": null,
                "SupervisorApprovedBy": null,
                "Id": "9279e283-45f9-5df0-805f-64a5469eda3a",
                "CreatedBy": "81300006@unitedtractors.com",
                "CreatedDate": "2020-04-21T09:49:49.894",
                "UpdatedBy": "81300006@unitedtractors.com",
                "UpdatedDate": "2020-04-21T09:49:49.894",
                "IsActive": true
            },
            {
                "WoId": "47284214-faf8-464f-a967-d26a8cf0675e",
                "BacklogId": null,
                "WoNumber": "70156080",
                "UnitModel": "HD785-7",
                "SerialNumber": "9402",
                "UnitCode": "DT4112",
                "EquipmentNumber": "106921",
                "FormNumber": "HD785-7/3402/00/QA10/13(5)",
                "ZoneDesc": "ZONE 1 FRONT & UPPER AREA",
                "AreaDesc": "A. FRONT SIDE OF MACHINE CHECK",
                "ItemDesc": "Shutdown switch & lockout switch function and condition.",
                "Version": "1.00",
                "Measurement": "0",
                "Sequence": 2,
                "MPriority": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MNote": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MCondition": {
                    "Measurement": null,
                    "TypeDesc": "0",
                    "Code": "NMG",
                    "Desc": "Good",
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "Comment": null,
                "LeaderApprovedBy": "80101070@unitedtractors.com",
                "LeaderApprovedDate": "2020-04-21T10:02:03.292",
                "SupervisorApprovedDate": null,
                "SupervisorApprovedBy": null,
                "Id": "613925d4-bb71-5baa-8eae-be0f56fa3acf",
                "CreatedBy": "81300006@unitedtractors.com",
                "CreatedDate": "2020-04-21T09:49:49.904",
                "UpdatedBy": "81300006@unitedtractors.com",
                "UpdatedDate": "2020-04-21T09:49:49.904",
                "IsActive": true
            },
            {
                "WoId": "47284214-faf8-464f-a967-d26a8cf0675e",
                "BacklogId": null,
                "WoNumber": "70156080",
                "UnitModel": "HD785-7",
                "SerialNumber": "9402",
                "UnitCode": "DT4112",
                "EquipmentNumber": "106921",
                "FormNumber": "HD785-7/3402/00/QA10/13(5)",
                "ZoneDesc": "ZONE 1 FRONT & UPPER AREA",
                "AreaDesc": "A. FRONT SIDE OF MACHINE CHECK",
                "ItemDesc": "Radiator fin and grille, unit code no. , after cooler, ac condenser,  oil cooler, hoses and mounting bolts check condition.",
                "Version": "1.00",
                "Measurement": "0",
                "Sequence": 3,
                "MPriority": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MNote": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MCondition": {
                    "Measurement": null,
                    "TypeDesc": "0",
                    "Code": "NMG",
                    "Desc": "Good",
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "Comment": null,
                "LeaderApprovedBy": "80101070@unitedtractors.com",
                "LeaderApprovedDate": "2020-04-21T10:02:03.292",
                "SupervisorApprovedDate": null,
                "SupervisorApprovedBy": null,
                "Id": "cd499279-41de-5b07-acdb-1111ab54472e",
                "CreatedBy": "81300006@unitedtractors.com",
                "CreatedDate": "2020-04-21T09:49:49.912",
                "UpdatedBy": "81300006@unitedtractors.com",
                "UpdatedDate": "2020-04-21T09:49:49.912",
                "IsActive": true
            },
            {
                "WoId": "47284214-faf8-464f-a967-d26a8cf0675e",
                "BacklogId": null,
                "WoNumber": "70156080",
                "UnitModel": "HD785-7",
                "SerialNumber": "9402",
                "UnitCode": "DT4112",
                "EquipmentNumber": "106921",
                "FormNumber": "HD785-7/3402/00/QA10/13(5)",
                "ZoneDesc": "ZONE 1 FRONT & UPPER AREA",
                "AreaDesc": "A. FRONT SIDE OF MACHINE CHECK",
                "ItemDesc": "Work lamp function and condition",
                "Version": "1.00",
                "Measurement": "0",
                "Sequence": 4,
                "MPriority": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MNote": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MCondition": {
                    "Measurement": null,
                    "TypeDesc": "0",
                    "Code": "NMG",
                    "Desc": "Good",
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "Comment": null,
                "LeaderApprovedBy": "80101070@unitedtractors.com",
                "LeaderApprovedDate": "2020-04-21T10:02:03.292",
                "SupervisorApprovedDate": null,
                "SupervisorApprovedBy": null,
                "Id": "d945f778-f49e-52d3-8b1f-a3365a3ba4eb",
                "CreatedBy": "81300006@unitedtractors.com",
                "CreatedDate": "2020-04-21T09:49:49.921",
                "UpdatedBy": "81300006@unitedtractors.com",
                "UpdatedDate": "2020-04-21T09:49:49.921",
                "IsActive": true
            },
            {
                "WoId": "47284214-faf8-464f-a967-d26a8cf0675e",
                "BacklogId": null,
                "WoNumber": "70156080",
                "UnitModel": "HD785-7",
                "SerialNumber": "9402",
                "UnitCode": "DT4112",
                "EquipmentNumber": "106921",
                "FormNumber": "HD785-7/3402/00/QA10/13(5)",
                "ZoneDesc": "ZONE 1 FRONT & UPPER AREA",
                "AreaDesc": "A. FRONT SIDE OF MACHINE CHECK",
                "ItemDesc": "Rotary (Accessories) check function",
                "Version": "1.00",
                "Measurement": "0",
                "Sequence": 5,
                "MPriority": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MNote": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MCondition": {
                    "Measurement": null,
                    "TypeDesc": "0",
                    "Code": "NMG",
                    "Desc": "Good",
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "Comment": null,
                "LeaderApprovedBy": "80101070@unitedtractors.com",
                "LeaderApprovedDate": "2020-04-21T10:02:03.292",
                "SupervisorApprovedDate": null,
                "SupervisorApprovedBy": null,
                "Id": "e5789900-adfb-52b5-9e67-8fc57faf93ab",
                "CreatedBy": "81300006@unitedtractors.com",
                "CreatedDate": "2020-04-21T09:49:49.932",
                "UpdatedBy": "81300006@unitedtractors.com",
                "UpdatedDate": "2020-04-21T09:49:49.932",
                "IsActive": true
            },
            {
                "WoId": "47284214-faf8-464f-a967-d26a8cf0675e",
                "BacklogId": null,
                "WoNumber": "70156080",
                "UnitModel": "HD785-7",
                "SerialNumber": "9402",
                "UnitCode": "DT4112",
                "EquipmentNumber": "106921",
                "FormNumber": "HD785-7/3402/00/QA10/13(5)",
                "ZoneDesc": "ZONE 1 FRONT & UPPER AREA",
                "AreaDesc": "A. FRONT SIDE OF MACHINE CHECK",
                "ItemDesc": "LH & RH Front Turn Lamp/Clearance Lamp check function.",
                "Version": "1.00",
                "Measurement": "0",
                "Sequence": 6,
                "MPriority": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MNote": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MCondition": {
                    "Measurement": null,
                    "TypeDesc": "0",
                    "Code": "NMG",
                    "Desc": "Good",
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "Comment": null,
                "LeaderApprovedBy": "80101070@unitedtractors.com",
                "LeaderApprovedDate": "2020-04-21T10:02:03.293",
                "SupervisorApprovedDate": null,
                "SupervisorApprovedBy": null,
                "Id": "975408ee-54aa-5764-bb5a-137b7002e9da",
                "CreatedBy": "81300006@unitedtractors.com",
                "CreatedDate": "2020-04-21T09:49:49.94",
                "UpdatedBy": "81300006@unitedtractors.com",
                "UpdatedDate": "2020-04-21T09:49:49.94",
                "IsActive": true
            },
            {
                "WoId": "47284214-faf8-464f-a967-d26a8cf0675e",
                "BacklogId": null,
                "WoNumber": "70156080",
                "UnitModel": "HD785-7",
                "SerialNumber": "9402",
                "UnitCode": "DT4112",
                "EquipmentNumber": "106921",
                "FormNumber": "HD785-7/3402/00/QA10/13(5)",
                "ZoneDesc": "ZONE 1 FRONT & UPPER AREA",
                "AreaDesc": "A. FRONT SIDE OF MACHINE CHECK",
                "ItemDesc": "Emergency Shutdown check condition",
                "Version": "1.00",
                "Measurement": "0",
                "Sequence": 7,
                "MPriority": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MNote": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MCondition": {
                    "Measurement": null,
                    "TypeDesc": "0",
                    "Code": "NMG",
                    "Desc": "Good",
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "Comment": null,
                "LeaderApprovedBy": "80101070@unitedtractors.com",
                "LeaderApprovedDate": "2020-04-21T10:02:03.293",
                "SupervisorApprovedDate": null,
                "SupervisorApprovedBy": null,
                "Id": "83eaa8ed-7ceb-53cf-ba9b-5c063a79bcfb",
                "CreatedBy": "81300006@unitedtractors.com",
                "CreatedDate": "2020-04-21T09:49:49.95",
                "UpdatedBy": "81300006@unitedtractors.com",
                "UpdatedDate": "2020-04-21T09:49:49.95",
                "IsActive": true
            },
            {
                "WoId": "47284214-faf8-464f-a967-d26a8cf0675e",
                "BacklogId": null,
                "WoNumber": "70156080",
                "UnitModel": "HD785-7",
                "SerialNumber": "9402",
                "UnitCode": "DT4112",
                "EquipmentNumber": "106921",
                "FormNumber": "HD785-7/3402/00/QA10/13(5)",
                "ZoneDesc": "ZONE 1 FRONT & UPPER AREA",
                "AreaDesc": "A. FRONT SIDE OF MACHINE CHECK",
                "ItemDesc": "LH Step Ladder check condition",
                "Version": "1.00",
                "Measurement": "0",
                "Sequence": 8,
                "MPriority": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MNote": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MCondition": {
                    "Measurement": null,
                    "TypeDesc": "0",
                    "Code": "NMG",
                    "Desc": "Good",
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "Comment": null,
                "LeaderApprovedBy": "80101070@unitedtractors.com",
                "LeaderApprovedDate": "2020-04-21T10:02:03.293",
                "SupervisorApprovedDate": null,
                "SupervisorApprovedBy": null,
                "Id": "7a631e78-9d05-5432-9253-2320b13c4ed9",
                "CreatedBy": "81300006@unitedtractors.com",
                "CreatedDate": "2020-04-21T09:49:49.959",
                "UpdatedBy": "81300006@unitedtractors.com",
                "UpdatedDate": "2020-04-21T09:49:49.959",
                "IsActive": true
            },
            {
                "WoId": "47284214-faf8-464f-a967-d26a8cf0675e",
                "BacklogId": null,
                "WoNumber": "70156080",
                "UnitModel": "HD785-7",
                "SerialNumber": "9402",
                "UnitCode": "DT4112",
                "EquipmentNumber": "106921",
                "FormNumber": "HD785-7/3402/00/QA10/13(5)",
                "ZoneDesc": "ZONE 1 FRONT & UPPER AREA",
                "AreaDesc": "A. FRONT SIDE OF MACHINE CHECK",
                "ItemDesc": "RH Step Ladder check condition",
                "Version": "1.00",
                "Measurement": "0",
                "Sequence": 9,
                "MPriority": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MNote": {
                    "Code": null,
                    "Desc": null,
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "MCondition": {
                    "Measurement": null,
                    "TypeDesc": "0",
                    "Code": "NMG",
                    "Desc": "Good",
                    "Sequence": null,
                    "Id": null,
                    "CreatedBy": null,
                    "CreatedDate": null,
                    "UpdatedBy": null,
                    "UpdatedDate": null,
                    "IsActive": false
                },
                "Comment": null,
                "LeaderApprovedBy": "80101070@unitedtractors.com",
                "LeaderApprovedDate": "2020-04-21T10:02:03.293",
                "SupervisorApprovedDate": null,
                "SupervisorApprovedBy": null,
                "Id": "50b21f93-a2ca-5f79-afaf-d7c3965b561d",
                "CreatedBy": "81300006@unitedtractors.com",
                "CreatedDate": "2020-04-21T09:49:49.968",
                "UpdatedBy": "81300006@unitedtractors.com",
                "UpdatedDate": "2020-04-21T09:49:49.968",
                "IsActive": true
            }
        ]
    }
]